name: kwiz
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  decorated_icon: null
  firebase_auth: ^0.18.4+1
  firebase_core: null
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.11.0
  get: ^3.24.0
  rflutter_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
